### ISSUE TITLE
using makecell with tabu is incompatible with tcolorbox and/or todonotes

### ISSUE THREAD

**Issue by nr87** [tabu-fixed/tabu#15]
My MWE:

> \documentclass[a4paper]{scrreprt}
> \usepackage{tcolorbox}
> \usepackage{todonotes}
> \usepackage{tabu,makecell}
> \begin{document}
> \noindent \begin{tabu} to \textwidth {@{}lXX}
> normal line & A & B \\
> line with makecell & \makecell[tl]{A\\C} & \makecell[tl]{B\\D\\E}
> \end{tabu}
> \todo{To Do: ...}
> \end{document}

When I exclude the line with \makecell, everything works. Also when I exclude the packages todo and tcolorbox (and of course, the line with \todo command, but keep the line with \makecell), everything works.

The problem occurs when I include at least one of the packages tcolorbox or todonotes. Then I got the following error:

> ./test-tabu.tex:9: Improper \prevdepth.
> \tabu@verticalspacing ...tempdimc \the \prevdepth 
>                                               \@tempdima \dimexpr \ht 
> \t...
> l.9 \end{tabu}

Perhaps someone know how to fix this? I would very much appreciate.

**Comment by FrankMittelbach** [comment]
Next time please include an MWE using "code" tags (your's lost several backslashes).

Anyway, your MWE works fine with the .sty file in this repository (which hasn't yet made it to CTAN) but will eventually.
