### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by digitig** [tabu-fixed/tabu#16]
Running latex tabu.ins gives the error:

> entering extended mode                             
(tabu.ins                                          
LaTeX2e <2018-12-01>                               
! Undefined control sequence.                      
l.2 \endbatchfile                

Running latex tabu.dtx gives the error:

> ! Package zref Error: Property `zen@default,zen@page,zen@type,zen@depth, zen@listctr,zen@listname,zen@index,zen@label,zen@ref,zen@starlabel,zen@parents,
zen@ref item,zen@commaref,zen@item,zen@currentlabel,zen@counter' does not exist.

(Perhaps the package needs installation instructions if installation isn't the usual process.)

**Comment by FrankMittelbach** [comment]
The whole tabu business are emergency fixes and for a number of reasons we can't maintain the .dtx file, so extraction from there is currently disabled.
