### ISSUE TITLE
Update links on CTAN, `tabu-fixed` -> `tabu-issues-for-future-maintainer`

### ISSUE THREAD

**Issue by muzimuzhi** [tabu-fixed/tabu#28]
Update CTAN entries to reflect the renaming of GitHub organization (from `tabu-fixed` to `tabu-issues-for-future-maintainer`):

On CTAN (https://ctan.org/pkg/tabu):
> Bug tracker | https://github.com/tabu-fixed/tabu/issues
> Repository | https://github.com/tabu-fixed/tabu

Although GitHub will correctly redirect the old URLs, the name `tabu-fixed` may give users wrong info (about the usability and maintaining state of `tabu`).

**Comment by davidcarlisle** [comment]
Ah yes thanks, we don't have direct access to the catalogue of course, but I'll send ctan an email

**Comment by davidcarlisle** [comment]
Petra has updated the ctan catalogue and the  github URL is now updated, and the maintainer shown as inactive at
https://ctan.org/pkg/tabu

**Comment by muzimuzhi** [comment]
Thanks for the quick response/action.  I notice the `Bug tracker` entry is lost, is that an unavoidable result of marking the maintainer inactive? Cause I think this repo still accepts (or welcomes? sort of) issues.

**Comment by davidcarlisle** [comment]
@muzimuzhi  to be honest I'm not sure really. As I say I left the details to the ctan maintainers. I think it's Ok as it is, the link to this repository is here and the issue link is easy enough to find from that.
