### ISSUE TITLE
tabulars in tabu might now be broken

### ISSUE THREAD

**Issue by sergiocallegari** [tabu-fixed/tabu#7]
Nesting tabulars in tabu tabulars may seem a weird thing to do.  The fact is that the "awesome" box package uses tabu internally to put admonition blocks around text to inform or alert
readers about something particular and it may well happen to have the need for such an admonition block on the side of a piece of text including a tabular.

Recently, the ability of awesomebox to properly decorate text that includes tabulars is broken.

Because awesomebox is simple and not rapid changing code, the suspect is tabu.
As of today, I am not 100% sure that the problem is with tabu, since I'll need to look into how awesomebox uses it to try to distill a minimal test case, but this issue is an early warning.

**Comment by FrankMittelbach** [comment]
will track under #1. Current code already fixes that but is not final
